### ISSUE TITLE
你好，请问您的项目 TopFreeProxies 为什么无法访问了？

### ISSUE THREAD

**Issue by ghost** [aiirobyte/logseq-task-automation#1]
我无法访问您的项目TopFreeProxies，呜呜呜

**Comment by aiirobyte** [comment]
> <img width="653" alt="image" src="https://user-images.githubusercontent.com/73283555/213909852-2468a21e-8e3e-4893-83db-0660bba316a2.png">
Response from GitHub Support, and I have created a [GitLab Repo](https://gitlab.com/nomorewalls/topfreeproxies).

**Comment by ghost** [comment]
> > <img alt="image" width="653" src="https://user-images.githubusercontent.com/73283555/213909852-2468a21e-8e3e-4893-83db-0660bba316a2.png">
> 
> Response from GitHub Support, and I have created a [GitLab Repo](https://gitlab.com/nomorewalls/topfreeproxies).

我的天那，github管理员也是用这个回复关闭了我的项目，好难过，呜呜呜

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/94947393/213915799-62252c16-7f02-4310-b6ca-7a221a16454a.png)
没有访问成功，呜呜呜

**Comment by aiirobyte** [comment]
> ![image](https://user-images.githubusercontent.com/94947393/213915799-62252c16-7f02-4310-b6ca-7a221a16454a.png) 没有访问成功，呜呜呜

不好意思上面的仓库是私有的🤦‍♂️，这个是公开的仓库： https://gitlab.com/aiirobyte/topfreeproxies

**Comment by ghost** [comment]
> > ![image](https://user-images.githubusercontent.com/94947393/213915799-62252c16-7f02-4310-b6ca-7a221a16454a.png) 没有访问成功，呜呜呜
> 
> 不好意思上面的仓库是私有的🤦‍♂️，这个是公开的仓库： https://gitlab.com/aiirobyte/topfreeproxies

谢谢您，刚看到，好人一生平安，太感谢了
